apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: test-app-167041079
  name: python
  namespace: l7m5igdq
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python
    weight: 100
status: {}
